name: Go

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Set up Go
      uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o ./bin/ ./...

    - name: Test
      run: go test -v ./...

    - name: Debug
      run: ls -la

    - name: Release
      uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          bin/hd1conman
          LICENSE
          README.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
